[tool.poetry]
name = "avro-to-python"
version = "0.1.0"
description = ""
authors = ["Dan Green-Leipciger <dangreen.tlv@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
astor = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate_typed_dict = "avro_to_python:generate_typed_dict"
to_typed_dict = "avro_to_python:typed_dict"