version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  format:
    executor:
      name: python/default
      tag: "3.9"
    steps: 
      - checkout
      - python/install-packages:
          pkg-manager: poetry    
      - run: poetry run black . --check

  build-and-test:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry      
      - run: poetry run pytest

workflows:
  main:
    jobs:
      - build-and-test
      - format
