name: Publish Release
on: 
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: |
          pip install poetry
      - name: Build package
        run: |
          poetry build
      - name: Publish
        run: |
          poetry publish --username=__token__ --password='${{ secrets.PYPI_TOKEN}}'
